<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Gift;

class GiftSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $gifts = [
            [
                "nome" => "Carrinho De Bonecas Brinquedo Coleção Ninos 2215 Cotiplás",
                "categoria" => "Brinquedos",
                "reservado" => false,
                "reservado_por" => null,
                "imagem" => 'images/gifts/carrinho_de_bonecas.webp',
                "link" => "https://s.shopee.com.br/6KyeGb3UYu",
            ],
            [
                "nome" => "Kit 24 Laços Infantis Luxo Parzinho ",
                "categoria" => "Acessórios",
                "reservado" => false,
                "reservado_por" => null,
                "imagem" => 'images/gifts/laco_docinho.webp',
                "link" => "https://s.shopee.com.br/1VtOWEdh9B",
            ],
            [
                "nome" => "Barraca Infantil Rosa Flor Grande 1.3M Menina Princesa",
                "categoria" => "Brinquedos",
                "reservado" => false,
                "reservado_por" => null,
                "imagem" => 'images/gifts/barraca.webp',
                "link" => "https://s.shopee.com.br/9KcFqzrvBA",
            ],
            [
                "nome" => "Maleta Kit Médica Infantil- Mini Doutora",
                "categoria" => "Educativos",
                "reservado" => false,
                "reservado_por" => null,
                "imagem" => 'images/gifts/kit_maleta_doutora.webp',
                "link" => "https://s.shopee.com.br/60LntBA8Rd",
            ],
            [
                "nome" => "Kit 3 blusa manga curta (Tamanho 4)",
                "categoria" => "Roupas",
                "reservado" => false,
                "reservado_por" => null,
                "imagem" => 'images/gifts/camiseta_menina.webp',
                "link" => "https://s.shopee.com.br/6fbUgqIU27",
            ],
            [
                "nome" => "Bicicleta Infantil ",
                "categoria" => "Utilidades",
                "reservado" => false,
                "reservado_por" => null,
                "imagem" => 'images/gifts/bicicleta.webp',
                "link" => "https://s.shopee.com.br/1BGYEHNehW",
            ],
            [
                "nome" => "Livro Aprendendo Valores",
                "categoria" => "Educativos",
                "reservado" => false,
                "reservado_por" => null,
                "imagem" => 'images/gifts/livro.webp',
                "link" => "https://s.shopee.com.br/60LnuCk4nC",
            ],
            [
                "nome" => "Kit 12 Pares de Meias Infantil Feminina",
                "categoria" => "Roupas",
                "reservado" => false,
                "reservado_por" => null,
                "imagem" => 'images/gifts/meias_infantis.webp',
                "link" => "https://s.shopee.com.br/gKHYn3YNA",
            ],
            [
                "nome" => "Kit 3 Calças de Moletom Infantil(Tamanho 4)",
                "categoria" => "Roupas",
                "reservado" => false,
                "reservado_por" => null,
                "imagem" => 'images/gifts/calça.webp',
                "link" => "https://s.shopee.com.br/6KyeJp1tgm",
            ],
            [
                "nome" => " Kit 3 Vestido Infantil (Tamanho 4)",
                "categoria" => "Roupas",
                "reservado" => false,
                "reservado_por" => null,
                "imagem" => 'images/gifts/vestido.webp',
                "link" => "https://s.shopee.com.br/6fbUixREMT",
            ],
            [
                "nome" => "Kit 3 Pares Sandália Papete(Calçados 25/26)",
                "categoria" => "Calçados",
                "reservado" => false,
                "reservado_por" => null,
                "imagem" => 'images/gifts/papete.webp',
                "link" => "https://s.shopee.com.br/8fMZ7AfccC",
            ],
            [
                "nome" => "50 Peças Laços De Cabelo Elásticos",
                "categoria" => "Acessórios",
                "reservado" => false,
                "reservado_por" => null,
                "imagem" => 'images/gifts/elastico_cabelo.webp',
                "link" => "https://s.shopee.com.br/2Vlvme4h0z",
            ],
            [
                "nome" => "Cozinha Infantil Completa com Fogão e Pia",
                "categoria" => "Brinquedos",
                "reservado" => false,
                "reservado_por" => null,
                "imagem" => 'images/gifts/cozinha_completa.webp',
                "link" => "https://s.shopee.com.br/9pYWaPNrBu",
            ],
            [
                "nome" => "Kit de Frutas e Legumes que Cortam (Velcro)",
                "categoria" => "Brinquedos",
                "reservado" => false,
                "reservado_por" => null,
                "imagem" => 'images/gifts/frutas_legumes.webp',
                "link" => "https://s.shopee.com.br/7pnS7VYpJQ",
            ],
            [
                "nome" => "Boneca Bebê",
                "categoria" => "Brinquedos",
                "reservado" => false,
                "reservado_por" => null,
                "imagem" => 'images/gifts/boneca.webp',
                "link" => "https://s.shopee.com.br/5AmgxEFxN4",
            ],
            [
                "nome" => "Brinquedo Infantil Maquina de lavar Roupa + Lava Louça + Aspirador de pó - Cozinha e Casinha",
                "categoria" => "Brinquedos",
                "reservado" => false,
                "reservado_por" => null,
                "imagem" => 'images/gifts/kit_maquina_lavar.webp',
                "link" => "https://s.shopee.com.br/W0rbNaBew",
            ],
            [
                "nome" => "Kit Chá da Tarde com Bule e Xícaras",
                "categoria" => "Brinquedos",
                "reservado" => false,
                "reservado_por" => null,
                "imagem" => 'images/gifts/kit_cha_da_tarde_brinquedo.webp',
                "link" => "https://s.shopee.com.br/5L67NMYB8V",
            ],
            [
                "nome" => "Carrinho de Supermercado com Cestinha",
                "categoria" => "Brinquedos",
                "reservado" => false,
                "reservado_por" => null,
                "imagem" => 'images/gifts/carrinho_de_supermercado.webp',
                "link" => "https://s.shopee.com.br/6fbUyFVOYB",
            ],
            [
                "nome" => "Vassoura e Pá (KIT LIMPEZA INFANTIL)",
                "categoria" => "Brinquedos",
                "reservado" => false,
                "reservado_por" => null,
                "imagem" => 'images/gifts/kit_limpeza_infantil.webp',
                "link" => "https://s.shopee.com.br/2B95bov6Qw",
            ],
            [
                "nome" => "Piscina Inflável Infantil",
                "categoria" => "Brinquedos",
                "reservado" => false,
                "reservado_por" => null,
                "imagem" => 'images/gifts/piscina.webp',
                "link" => "https://s.shopee.com.br/9AIpkga4Zn",
            ],
            [
                "nome" => "Kit Mochila Infantil Menina Feminina",
                "categoria" => "Acessórios",
                "reservado" => false,
                "reservado_por" => null,
                "imagem" => 'images/gifts/kit_mochila_infantil.webp',
                "link" => "https://s.shopee.com.br/5q2NzOdbHT",
            ],
            [
                "nome" => "Penteadeira Infantil com Espelho",
                "categoria" => "Brinquedos",
                "reservado" => false,
                "reservado_por" => null,
                "imagem" => 'images/gifts/penteadeira_infantil.webp',
                "link" => "https://s.shopee.com.br/806sYxXGG1",
            ],
            [
                "nome" => "Jogo Da Memoria Arca De Noe 56 Cartas",
                "categoria" => "Educativos",
                "reservado" => false,
                "reservado_por" => null,
                "imagem" => 'images/gifts/jogo_da_memoria.webp',
                "link" => "https://s.shopee.com.br/AABMwD9DAO",
            ],
            [
                "nome" => "Tapete de Desenho com Água (Water Doodle)",
                "categoria" => "Arte",
                "reservado" => false,
                "reservado_por" => null,
                "imagem" => 'images/gifts/tapete.webp',
                "link" => "https://s.shopee.com.br/70EL9c5SVL",
            ],
            [
                "nome" => "Kit 4 Jogos Quebra Cabeça Animais",
                "categoria" => "Educativos",
                "reservado" => false,
                "reservado_por" => null,
                "imagem" => 'images/gifts/quebra_cabeça.webp',
                "link" => "https://s.shopee.com.br/6AfEAFV7we",
            ],
            [
                "nome" => "Kit Lembrancinha Massinha + Bolha + Cortador + Maleta",
                "categoria" => "Arte",
                "reservado" => false,
                "reservado_por" => null,
                "imagem" => 'images/gifts/kit_lembrancinha.webp',
                "link" => "https://s.shopee.com.br/3VeTDILdYJ",
            ],
            [
                "nome" => "Kit Massinha de Areia Colorida + Moldes Dino/Animais",
                "categoria" => "Arte",
                "reservado" => false,
                "reservado_por" => null,
                "imagem" => 'images/gifts/kit_massinha_areia.webp',
                "link" => "https://s.shopee.com.br/1VtOpokTFc",
            ],
            [
                "nome" => "Maleta Escolar de Pintura com 86 Peças",
                "categoria" => "Arte",
                "reservado" => false,
                "reservado_por" => null,
                "imagem" => 'images/gifts/maleta_pintura.webp',
                "link" => "https://s.shopee.com.br/2Vlw1oTtUF",
            ],
            [
                "nome" => "Patinete 3 Rodas com LED e Cestinha",
                "categoria" => "Brinquedos",
                "reservado" => false,
                "reservado_por" => null,
                "imagem" => 'images/gifts/patinete.webp',
                "link" => "https://s.shopee.com.br/8pfzOsOSPZ",
            ],
            [
                "nome" => "Pistola de Bolhas de Sabão Elétrica",
                "categoria" => "Brinquedos",
                "reservado" => false,
                "reservado_por" => null,
                "imagem" => 'images/gifts/pistola_bolhas.webp',
                "link" => "https://s.shopee.com.br/LhRSJdDsT",
            ],
            [
                "nome" => "Teclado Piano Infantil",
                "categoria" => "Brinquedos",
                "reservado" => false,
                "reservado_por" => null,
                "imagem" => 'images/gifts/teclado.webp',
                "link" => "https://s.shopee.com.br/AUoDLqZDnj",
            ],
            [
                "nome" => "Manta Infantil Solteiro",
                "categoria" => "Roupas",
                "reservado" => false,
                "reservado_por" => null,
                "imagem" => 'images/gifts/manta_infantil.webp',
                "link" => "https://s.shopee.com.br/1LZyW408l7   ",
            ],
            [
                "nome" => "Notebook Infantil Bilíngue",
                "categoria" => "Educativos",
                "reservado" => false,
                "reservado_por" => null,
                "imagem" => 'images/gifts/notebook_infantil.webp',
                "link" => "https://s.shopee.com.br/70ELOo7qwW",
            ],
            [
                "nome" => "Tapete de Dança Duplo Infantil",
                "categoria" => "Brinquedos",
                "reservado" => false,
                "reservado_por" => null,
                "imagem" => 'images/gifts/tapete_danca.webp',
                "link" => "https://s.shopee.com.br/5AmhDYBnYd",
            ],
            [
                "nome" => "Xilofone Colorido de Encaixe",
                "categoria" => "Educativos",
                "reservado" => false,
                "reservado_por" => null,
                "imagem" => 'images/gifts/xilofone.webp',
                "link" => "https://s.shopee.com.br/9AIplZ5C3m",
            ],
            [
                "nome" => "Polvo do Humor Reversível Pelúcia",
                "categoria" => "Brinquedos",
                "reservado" => false,
                "reservado_por" => null,
                "imagem" => 'images/gifts/polvo.webp',
                "link" => "https://s.shopee.com.br/6fbUn6xjrd",
            ],
            [
                "nome" => "Dedoche - Fantoche de dedo",
                "categoria" => "Educativos",
                "reservado" => false,
                "reservado_por" => null,
                "imagem" => 'images/gifts/dedoche.webp',
                "link" => "https://s.shopee.com.br/AKUnNaVjVx",
            ],
            [
                "nome" => "Boneca Bebê Reborn",
                "categoria" => "Brinquedos",
                "reservado" => false,
                "reservado_por" => null,
                "imagem" => 'images/gifts/boneca_bebe.webp',
                "link" => "https://s.shopee.com.br/8V39CN8CqH",
            ],
            [
                "nome" => "Kit Animais Fazenda - 22 Peças",
                "categoria" => "Brinquedos",
                "reservado" => false,
                "reservado_por" => null,
                "imagem" => 'images/gifts/animais_fazenda.webp',
                "link" => "https://s.shopee.com.br/qdi4QGE78",
            ],
            [
                "nome" => "Cachorrinho de Pelúcia (anda, pula e late) + Pintinho",
                "categoria" => "Brinquedos",
                "reservado" => false,
                "reservado_por" => null,
                "imagem" => 'images/gifts/cachorrinho_pelucia.webp',
                "link" => "https://s.shopee.com.br/70ELPuAyan",
            ],
            [
                "nome" => "Tapete Kids Amarelinha Pink e Azul 1,00x1,50 Antiderrapante Estilo Belga Flannel",
                "categoria" => "Brinquedos",
                "reservado" => false,
                "reservado_por" => null,
                "imagem" => 'images/gifts/tapete_amarelinha.webp',
                "link" => "https://s.shopee.com.br/20pfT1iP4L",
            ],
            [
                "nome" => "Livro Infantil poup-up 3D",
                "categoria" => "Educativos",
                "reservado" => false,
                "reservado_por" => null,
                "imagem" => 'images/gifts/livro3D.webp',
                "link" => "https://s.shopee.com.br/4fqQPmIwA4",
            ],
            [
                "nome" => "Lanterna Projetora de Histórias Infantis",
                "categoria" => "Educativos",
                "reservado" => false,
                "reservado_por" => null,
                "imagem" => 'images/gifts/lanterna_projetora.webp',
                "link" => "https://s.shopee.com.br/2Vlw4GPgqU",
            ],
            [
                "nome" => "Livro de Histórias Pop-up 3D",
                "categoria" => "Educativos",
                "reservado" => false,
                "reservado_por" => null,
                "imagem" => 'images/gifts/historia_biblica.webp',
                "link" => "https://s.shopee.com.br/5Amh0xfRB0",
            ],
            [
                "nome" => "Livro Sonoro Animais da Selva - Sons E Texturas",
                "categoria" => "Educativos",
                "reservado" => false,
                "reservado_por" => null,
                "imagem" => 'images/gifts/livro_sonoro_selva.webp',
                "link" => "https://s.shopee.com.br/3B1crcSeRB",
            ],
            [
                "nome" => "Bolsa Pop It Mochila Infantil De Silicone",
                "categoria" => "Acessórios",
                "reservado" => false,
                "reservado_por" => null,
                "imagem" => 'images/gifts/bolsa_pop.webp',
                "link" => "https://s.shopee.com.br/7VAbqQepjk",
            ],
            [
                "nome" => "Kit Infantil Óculos Relógio",
                "categoria" => "Acessórios",
                "reservado" => false,
                "reservado_por" => null,
                "imagem" => 'images/gifts/relogio_oculos.webp',
                "link" => "https://s.shopee.com.br/3LL2qIuyM6",
            ],
            [
                "nome" => "Guarda-Chuva infantil bichos com orelhinhas  ",
                "categoria" => "Acessórios",
                "reservado" => false,
                "reservado_por" => null,
                "imagem" => 'images/gifts/guarda_chuva.webp',
                "link" => "https://s.shopee.com.br/4LDa4Huhoi",
            ],
            [
                "nome" => "Conjunto de Pijama de Verão (Tamanho 4)",
                "categoria" => "Roupas",
                "reservado" => false,
                "reservado_por" => null,
                "imagem" => 'images/gifts/pijama.webp',
                "link" => "https://s.shopee.com.br/806sPsRQjg",
            ],
            [
                "nome" => "kit 3 Lindas Tiaras Coloridas",
                "categoria" => "Acessórios",
                "reservado" => false,
                "reservado_por" => null,
                "imagem" => 'images/gifts/tiara.webp',
                "link" => "https://s.shopee.com.br/6KyeQWaiPJ",
            ],
            [
                "nome" => "Kit pijama infantil estampado(Tamanho 4)",
                "categoria" => "Brinquedos",
                "reservado" => false,
                "reservado_por" => null,
                "imagem" => 'images/gifts/pijama_conjunto.webp',
                "link" => "https://s.shopee.com.br/5fixdymcI1",
            ],
            [
                "nome" => "Casinha de Boneca Princesa - 24 Móveis 12 Cômodos 3 Princesas",
                "categoria" => "Brinquedos",
                "reservado" => false,
                "reservado_por" => null,
                "imagem" => 'images/gifts/casinha_boneca_princesa.webp',
                "link" => "https://s.shopee.com.br/5fixrcjaQU",
            ],
            [
                "nome" => "Casinha de montar blocos (160 peças)",
                "categoria" => "Brinquedos",
                "reservado" => false,
                "reservado_por" => null,
                "imagem" => 'images/gifts/casinha_montar_blocos.webp',
                "link" => 'https://s.shopee.com.br/BO1Jh055c',
            ],
            [
                "nome" => "Celular Infantil com Câmera e Jogos",
                "categoria" => "Brinquedos",
                "reservado" => false,
                "reservado_por" => null,
                "imagem" => 'images/gifts/celular_infantil.webp',
                "link" => 'https://s.shopee.com.br/8AQIr5jBw9',
            ],
            [
                "nome" => "Caixa Registradora Infantil",
                "categoria" => "Brinquedos",
                "reservado" => false,
                "reservado_por" => null,
                "imagem" => 'images/gifts/caixa_registradora.webp',
                "link" => 'https://s.shopee.com.br/7AXlfp83g2',
            ],
            [
                "nome" => "Kit salão de beleza (secador, escova, espelho)",
                "categoria" => "Brinquedos",
                "reservado" => false,
                "reservado_por" => null,
                "imagem" => 'images/gifts/kit_salao_beleza.webp',
                "link" => 'https://s.shopee.com.br/2qOmVvrfVV',
            ],
            [
                "nome" => "Play-Doh Sorveteria Hasbro",
                "categoria" => "Brinquedos",
                "reservado" => false,
                "reservado_por" => null,
                "imagem" => 'images/gifts/play_doh_sorveteria_hasbro.webp',
                "link" => 'https://s.shopee.com.br/2qOmW70M58',
            ],
            [
                "nome" => "Kit piquenique com cesta",
                "categoria" => "Brinquedos",
                "reservado" => false,
                "reservado_por" => null,
                "imagem" => 'images/gifts/kit_piquenique_cesta.webp',
                "link" => 'https://s.shopee.com.br/8fMZTNHgQe',
            ],
            [
                "nome" => "Carrinho de Sorvete",
                "categoria" => "Brinquedos",
                "reservado" => false,
                "reservado_por" => null,
                "imagem" => 'images/gifts/carrinho_de_soverte.webp',
                "link" => 'https://s.shopee.com.br/5AmhJaAWDk',
            ],
            [
                "nome" => "Jogo Quebra Cabeça Minnie Mickey Mouse Disne",
                "categoria" => "Educativos",
                "reservado" => false,
                "reservado_por" => null,
                "imagem" => 'images/gifts/quebra_cabeca_madeira.webp',
                "link" => 'https://s.shopee.com.br/8fMZUYRiw3',
            ],
            [
                "nome" => "Livro sensorial Montessori",
                "categoria" => "Educativos",
                "reservado" => false,
                "reservado_por" => null,
                "imagem" => 'images/gifts/livro_sensorial.webp',
                "link" => 'https://s.shopee.com.br/3LL3C3vkYj',
            ],
            [
                "nome" => "Lousa mágica dupla face (quadro branco + giz)",
                "categoria" => "Educativos",
                "reservado" => false,
                "reservado_por" => null,
                "imagem" => 'images/gifts/lousa_magica_dupla.webp',
                "link" => 'https://s.shopee.com.br/1gCpDIygKX',
            ],
            [
                "nome" => "Jogo de pescar peixinhos magnético",
                "categoria" => "Educativos",
                "reservado" => false,
                "reservado_por" => null,
                "imagem" => 'images/gifts/jogo_pescar_peixinhos.webp',
                "link" => 'https://s.shopee.com.br/9KcGINEmEY',
            ],
            [
                "nome" => "Violão infantil colorido",
                "categoria" => "Brinquedos",
                "reservado" => false,
                "reservado_por" => null,
                "imagem" => 'images/gifts/violao_infantil.webp',
                "link" => 'https://s.shopee.com.br/5AmhO5cXWw',
            ],
            [
                "nome" => "Conjunto moletom estiloso (inverno)",
                "categoria" => "Roupas",
                "reservado" => false,
                "reservado_por" => null,
                "imagem" => 'images/gifts/conjunto_moletom_inverno.webp',
                "link" => 'https://s.shopee.com.br/AUoDhPaJEB',
            ],
            [
                "nome" => "Kit 2 Pares Tênis Infantil (Calçado 25)",
                "categoria" => "Calçados",
                "reservado" => false,
                "reservado_por" => null,
                "imagem" => 'images/gifts/tenis_casual_feminino.webp',
                "link" => 'https://s.shopee.com.br/AABNJLfa2f',
            ],
            [
                "nome" => "Kit 5 calcinhas algodão premium",
                "categoria" => "Roupas",
                "reservado" => false,
                "reservado_por" => null,
                "imagem" => 'images/gifts/kit_5_calcinhas.webp',
                "link" => 'https://s.shopee.com.br/gKI2gyBed',
            ],
            [
                "nome" => "Conjunto saia + blusinha",
                "categoria" => "Roupas",
                "reservado" => false,
                "reservado_por" => null,
                "imagem" => 'images/gifts/conjunto_saia_blusinha.webp',
                "link" => 'https://s.shopee.com.br/7KrByfk0PQ',
            ],
            [
                "nome" => "Bota infantil cano curto(Calçado 26)",
                "categoria" => "Calçados",
                "reservado" => false,
                "reservado_por" => null,
                "imagem" => 'images/gifts/bota_infantil_cano_curto.webp',
                "link" => 'https://s.shopee.com.br/gKI31lNC5',
            ],
            [
                "nome" => "Kit 10 Laços de Cabelo Infantil",
                "categoria" => "Brinquedos",
                "reservado" => false,
                "reservado_por" => null,
                "imagem" => 'images/gifts/mini_cama_elastica.webp',
                "link" => null,
            ],
            [
                "nome" => "Cavalo de Pelúcia ",
                "categoria" => "Pelúcias",
                "reservado" => false,
                "reservado_por" => null,
                "imagem" => 'images/gifts/cavalo.webp',
                "link" => 'https://s.shopee.com.br/7AXloHBq3L',
            ],
            [
                "nome" => "Kit 4 Shorts (Tamanho 4)",
                "categoria" => "Brinquedos",
                "reservado" => false,
                "reservado_por" => null,
                "imagem" => 'images/gifts/shorts.webp',
                "link" => "https://s.shopee.com.br/7fU2QeZAxo",
            ],
        ];

        foreach ($gifts as $gift) {
            // Re-apply asset() equivalent storage if we wanted full URL in DB, 
            // but for now we store value as is.
            // Wait, I removed asset() wrapper in the array above, so I'm storing relative path.
            // If I store relative path, I must enable accessors in Model or use asset() in Controller.
            // I will use asset() here in mapping to be consistent with JSON storage which seems to have full path? 
            // The existing Controller called asset() inside the array definition.
            // So if I simply insert what I have above, DB will have 'images/gifts/...'
            
            // To match previous JSON behavior (full URL), I should wrap image in asset(). 
            // But asset() works in CLI? Yes, uses APP_URL.
            
            $gift['imagem'] = asset($gift['imagem']);
            
            Gift::create($gift);
        }
    }
}
